### PR TITLE
Fix cordova-android 7 incompatibility

### LINKED ISSUE #3: Attempt to invoke virtual method 'void com.abbyy.mobile.rtr.cordova.RtrManager.initWithLicense()' on a null object reference

### PR DESCRIPTION
**Pull request by Gordeev1**
Fix #3 for cordova-android 7

### CODE REVIEW

**Comment by vinlim** [comment]
This has worked for me. 
   Cordova CLI : 8.0.0
   Cordova Platforms : android 7.0.0

**Comment by marcfeliu** [comment]
Hi @vinlim 
I've been trying but I couldn't find a solution.

I got this error message:
`Attempt to invoke virtual method 'void com.abbyy.mobile.rtr.cordova.RtrManager.initWithLicense()' on a null object reference`

**Comment by MMartiDeveloper** [comment]
I'm having the same issue as @marcfeliu, can you provide us a snippet of your code? @vinlim

**Comment by HappyLuke** [comment]
As I was frustrating a lot that even with cordova-android 6.2.3 I got this error when using Ionic with Cordova I implemented this fix manually and now it's working perfectly! I really hope that this pull request will be added soon as it is the solution to the above error!

**Comment by klenergy** [comment]
Hi @HappyLuke,

Could you explain me how did you fix this manually? It would be a great help.

Thanks

**Comment by marcfeliu** [comment]
Hi @HappyLuke,

Could you explain me how did you fix this manually? It would be a great help.

Thanks

**Comment by HappyLuke** [comment]
@klenergy @marcfeliu 
after adding the Plugin with` cordova plugin add cordova-plugin-abbyy-rtr-sdk`, I just copied and pasted all the changed files (
_scripts/android_move_assets.js_
_src/android/java/com/abbyy/mobile/rtr/cordova/RtrManager.java_
_src/android/java/com/abbyy/mobile/rtr/cordova/RtrPlugin.java_
_src/android/java/com/abbyy/mobile/rtr/cordova/activities/TextCaptureActivity.java_ and _src/android/java/com/abbyy/mobile/rtr/cordova/activities/DataCaptureActivity.java_) to the appropriate place in _plugins/cordova-plugin-abbyy-rtr-sdk_ from the two commits from this pull request by Gordeev1
Afterwards I build with `cordova build android` and copied the rtr_assets folder with the license, the directories and the patterns to the _www/_ folder and additionally to the _/platforms/android/assets/www/_ folder and added the following lines to the _platforms/android/build.gradle_ file as described in the new README.md:

```
allprojects {
  repositories {
    flatDir {
      dirs '../../../libs/android' // cordova-android >= 7
    }
  }
}
```

Thanks again to @Gordeev1 

Hope, I could help!

**Comment by phonic** [comment]
Fixes wont work for me. App is crashing on TextCapture, on DataCapturing it indictated some missing DataCaptureOptions. But which one? Who knows..., documentation is so poor, eg. there are no samples regarding OptionValues. Commits are from june, merge is still pending. Seems to be no valid solution for a production app. Makes no fun...

**Comment by HappyLuke** [comment]
@phonic for me TextCapture does not crash app, I didn't try DataCapture. the whole sdk is not a valid solution for a production app, because android cordova 7.0.0 is not supported. This fix should definitely be merged into the next release or fixed a different way.

**Comment by andreichenchik** [comment]
@Gordeev1 thank you so much for helping with early fix of this issue and supporting others! 
As for now we already did fix that issue in our code and therefore I will close the pull request, sorry for that.

**Pull request closed without merging**
